### ISSUE TITLE
The shortcode `details` tag not works.

### ISSUE THREAD

**Issue by wenchy** [h-enk/doks-child-theme#123]
## Description

I use the shortcode`details` with `doks-child-theme@0.4.0`, when execute `npm run start`, it broken with the error tip `failed to extract shortcode: template for shortcode "details" not found`.

### Steps to reproduce

1. Ceate a child-theme: `git clone https://github.com/h-enk/doks-child-theme.git my-doks-site`.
2. Add shortcode`details` at `content/en/docs/help/how-to-update.md`:
    ```
    {{< details "details test" open >}}
        Good job.
    {{< /details >}}
    ```
3. Run: `npm run start`

### Expected result

It should works in `doks-child-theme@0.4.0`.

### Actual result

An error happened:
```
failed to extract shortcode: template for shortcode "details" not found.
```

### Environment

```
> doks-child-theme@0.4.0 precheck
> npm version

{
  'doks-child-theme': '0.4.0',
  npm: '8.3.0',
  node: '17.3.0',
  v8: '9.6.180.15-node.12',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.46.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

> doks-child-theme@0.4.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.92.1-85E2E862+extended darwin/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
Yes, that's correct. Will be part of the upcoming release v0.4.1 — available soon

**Comment by h-enk** [comment]
Now part of Doks Child Theme [v0.4.1](https://github.com/h-enk/doks-child-theme/releases/tag/v0.4.1)
